const CHANNEL_ID = 'UCMqd1VhAkxcGC6AZRQW2ZmA';
const DEFAULT_TZ = 'America/Santo_Domingo';
const BASE_DATE_YMD = '2025-02-20';
const THUMB_FOLDER_ID = "1hiiAL0X_YchX56UdZbBX65uWgRhTGEZv";
const YT_PERMANENT_STREAM_KEY = "jecx-k82c-5s2g-rcms-0t4b";
const PERSISTENT_STREAM_ID = "Mqd1VhAkxcGC6AZRQW2ZmA1765924786826061";

// Playlists
const GENERAL_YT_PLAYLIST_ID = "REPLACE_WITH_GENERAL_YT_PLAYLIST_ID";
const HALF_MTM_PLAYLIST_ID = "REPLACE_WITH_HALF_MTM_PLAYLIST_ID";
const FULL_MTM_PLAYLIST_ID = "REPLACE_WITH_FULL_MTM_PLAYLIST_ID";
